[package]
name = "net-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
tokio.workspace = true
net-msg.workspace = true
cfg-server.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
