# Note: Any changes to this config will only take effect
# after restarting the game.

# For character IDs in lineup & owned_avatars
# Do not put multipath id. Use real id:
# trailblazer = 8001, march = 1001

# Editing this lineup only affects overworld lineup
lineup = [1201, 1001, 8001]

trailblazer_gender = "Woman"
trailblazer_element = "Imaginary"
march_element = "Imaginary"

# You don't need to update owned_avatars for battle to work.
# Only need to update for lineup.
# If you don't change the lineup, no need to update.

# Last updated: Fugue
owned_avatars = [
    1001,
    1002,
    1003,
    1004,
    1005,
    1006,
    1008,
    1009,
    1013,
    1101,
    1102,
    1103,
    1104,
    1105,
    1106,
    1107,
    1108,
    1109,
    1110,
    1111,
    1112,
    1201,
    1202,
    1203,
    1204,
    1205,
    1206,
    1207,
    1208,
    1209,
    1210,
    1211,
    1212,
    1213,
    1214,
    1215,
    1217,
    1218,
    1220,
    1221,
    1222,
    1223,
    1224,
    1225,
    1301,
    1302,
    1303,
    1304,
    1305,
    1306,
    1307,
    1308,
    1309,
    1310,
    1312,
    1313,
    1314,
    1315,
    1317,
    # 1401
    # 1402
    8001,
    # 8002
    # 8003
    # 8004
    # 8005
    # 8006
    # 8007
    # 8008
]